# Generated by Django 3.2.4 on 2021-06-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(max_length=200)),
                ('cabine_alloted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_employ', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('date_of_join', models.DateField()),
                ('no_of_fruits', models.IntegerField(default=0)),
                ('department_aloted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.department')),
            ],
        ),
    ]
